<!-- Footer-->
       <footer>
        <section id="contact">
            <div class="network1">
                <h2>Nous contacter</h2>
                <adress>
                    <p>Boite aux lettres devant l'école Jule Verne</p>
                    <i class="fas fa-map-marker-alt"></i>
                    7, rue Jules Verne 44420 LA TURBALLE<br>
                    <i class="fas fa-envelope"></i> <a href="mail:apejvlaturballe@gmail.com">apejvlaturballe@gmail.com
                    </a><br>
                    <div class="network2">
                        <p>Suivez-nous sur :</p>
                        <a href="https://www.facebook.com/APEJV44" target="_blank"><i
                                class="fab fa-2x fa-facebook-square"></i></a>


                    </div>
                </adress>

        </section>
    </footer>

</body>

</html>