<!DOCTYPE html>
<html lang="fr">

<head>

    <title>APE JV Association de parents d'élèves Jules Vernes La Turballe</title>
    <!--pour les accents-->
    <meta charset="utf-8">

    <!--adapté aux tailles des écrans-->
    <!--pour adapter aux tel portable-->
    <!--zoom de départ-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--icons-->

    <!--<script src="https://kit.fontawesome.com/3507128011.js" crossorigin="anonymous"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">


    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Athiti&family=Barriecito&family=Dancing+Script&family=Darumadrop+One&family=Fjalla+One&family=Merienda:wght@400;500;600&family=Nunito:wght@200&family=Parisienne&family=Roboto:ital,wght@1,900&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,600;0,700;1,200;1,300;1,400;1,600&family=Yuji+Hentaigana+Akari&display=swap"
        rel="stylesheet">

    <!--bootstrap-->
    <!-- Favicon -->
    <link rel="icon" href="favicon.png" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.png" />


    <!--styles-->
    <link href="assets/front/css/styles.css" rel="stylesheet" />
</head>

<body>
    <header>
        <div class="header">
            <div class="logo">
                <a href="?page=home"><img src="assets/front/images/logo.png"></a>
                <h1><span class="ape">Ape</span> <span class="j">J</span><span class="v">V</span></h1>
            </div>
            <h2>Association de parents d'élèves Jules Verne La Turballe</h2>
        </div>
        <div class="accueil">
            <ul>
                <li><a href="?page=home">Accueil</a></li>
                <li><a href="?page=ape">Présentation de l'APE</a></li>
                <li><a href="?page=team">Notre équipe</a></li>
                <li><a href="?page=apeInPicture">Nos évènements passés</a></li>
                <li><a href="?page=document">Documents</a></li>
                <li><a href="?page=order">Commandes</a></li>
                <li><a href="?page=contact">Contact</a></li>
            </ul>
        </div>
    </header>