
    <main class="presentation">
        <div class="What">
            <h2>L'APE c'est quoi ?</h2>
            <p>Le but de l'association est de proposer des activités festives, sportives et culturelles à destination
                des élèves et de leurs familles, activités à soutenir l'action éducative de l'équipe enseignante (aide
                au financement d'une s'ortie, d'un
                projet...). Mais aussi pour faire plaisir aux enfants lors des gros évènements de l'année (fête de
                l'école annuel, cadeaux de noël, pâques, lot pour les pêches à la ligne ...)</p>
            <p>Mais le rôle de l'APE est aussi d'accueillir les parents, informer, assurer les liens entre parents,
                équipe enseignante et directeurs d'école et représenter les familles lors de différentes réunions
                notamment aux conseils d'école aux cotés
                des parents d'élèves élus.</p>
        </div>
        <div class="Who">
            <h2>L'APE c'est qui ?</h2>
            <p>L'association est composée de parents bénévoles qui décident de s'investir pour les enfants. le conseil
                d'administration peut être composé de 12 membres</p>
            <p>Vous avez, c'est certain, quelque chose à apporter : du talent, du temps, des compétences... Mettez-les
                au service de l'APE et participez au différentes actions.</br>
                Chaque manifestations (vente divers, fête de l'école, manifestations proposé par la mairie de La
                Turballe...) est décidée et organisée collectivement.</p>
            <p>Que vous soyer disponible un peu, beaucoup, passionnément, à la folie...</p>
            <p>Rejoignez-nous !</p>
        </div>
        <div class="Or">
            <h2>L'APE c'est où ?</h2>
            <p>A l'école : une boîte est à votre disposition pour toutes correspondances(boite aux lettre à l'école
                primaire Jules Verne 7 Rue Jules Verne, 44420 La Turballe)</p>
            <p>Par téléphone :<a href="tel:+33683579698">06 83 57 96 98</a></p>
            <p>Par Mail :<a href="mail:apejvlaturballe@gmail.com">apejvlaturballe@gmail.com </a></p>
            <p>Sur la page facebook : <a href="https://www.facebook.com/APEJV44">www.facebook.com/APEJV44</a></p>
            <p>Sur notre site internet : <a href="http//www.ape-jv-la-turballe.fr">http//www.ape-jv-la-turballe.fr</a>
            </p>

        </div>
    </main>