    <main>
        <div class="animation">
            <h2>Nos animations</h2>
            <div class="haloween">
                <h3>Haloween</h3>
                <p>Chaque année nous proposons des maquillages, des gâteaux, et des boissons accompagnés des parents
                    bénévoles qui sont présents avec nous ce jour-là ou qui ont la gentillesse de nous faire de jolis
                    gâteaux.</p>
                <img src="assets/front/images/gateau-haloween.jpg"></img>
            </div>
            <div class="noel">
                <h3>Noël</h3>
                <p>Nous sommes présent chaque années lors du marché de Noël organisé par la ville de La Turballe.</p>
                <p>Nous vendons des gateaux réalisé par nos enfants et des choses également réalisé par les parents</p>
                <img src="assets/front/images/marche-noel.jpg"></img>
                <img src="assets/front/images/pain-d-épice.jpg"></img>
                <img src="assets/front/images/marche-noel-1.jpg"></img>
            </div>

        </div>

    </main>