    <article>
        <div class="form">
            <form action="#" method="post">
                <fieldset>
                    <legend>Mes coordonnées</legend>
                    <label>Nom</label>
                    <input type="text" name="nom"><br>
                    <label>Nom de votre enfant</label>
                    <input type="text" name="nom"><br>
                    <label>Classe de votre enfant</label>
                    <input type="text" name="nom"><br>
                    <label>Email:</label>
                    <input type="mail" name="nom"><br>
                    <label>Objet</label>
                    <input type="text" name="nom"><br>
                </fieldset>
                <fieldset>
                    <legend>Ma demande</legend>
                    <textarea name="mademande" id="" cols="30" rows="10"></textarea><br>
                    <input class="btn-submit" type="submit" value="Valider le formulaire">
                </fieldset>
            </form>
        </div>

    </article>


   