
    <main class="document">
        <h2>Retrouvez ci-dessous les résumés de nos diférentes réunions</h2>
        <div class="documents">
            <div class="generalAssemble">
                <h3>Nos Assemblées Générales</h3>
                <a href="assets/front/doc/agseptembre2022.pdf" download target="_blank">veuillez télécharger le document AG sep
                    2022</a>
            </div>
            <div class="diversDoc">
                <h3>Nos autres réunions</h3>
                <a href="assets/front/doc/CR_réunion préparation festivités_2023.pdf" download target="_blank">veuillez télécharger
                    préparation festivités_2023</a>
            </div>
        </div>

    </main>



    