
    <main>
        <div class="video">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/EqLMNIWBLBE"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowfullscreen></iframe>

        </div>
        <div class="diary">
            <h2>Nos prochaine dates à retenir</h2>
            <div class="agenda">
                <div class="date">
                    <div class="dates">
                        <p>Septembre</p>
                        <p>2023</p>
                    </div>
                    <div class="comment">
                        <ul> Assemblée Général</ul>
                    </div>
                </div>
                <div class="date">
                    <div class="dates">
                        <p>Mardi</p>
                        <p>31</p>
                        <p>Octobbre</p>
                    </div>
                    <div class="comment">
                        <ul> Haloween</ul>
                    </div>
                </div>
                <div class="date">
                    <div class="dates">
                        <p>Novembre</p>
                        <p>2023</p>
                    </div>
                    <div class="comment">
                        <ul> Vente Sapin</ul>
                    </div>
                </div>
                <div class="date">
                    <div class="dates">
                        <p>Décembre</p>
                        <p>2023</p>
                    </div>
                    <div class="comment">
                        <ul>Vente Chocolats de Noël</ul>
                    </div>
                </div>
            </div>
    </main>



    