    <main class="crew">
        <div class="president">
            <div class="president1">
                <img src="assets/front/images/photomarjorie.jpg">
            </div>
            <h3>Marjorie</h3>
            <p>Présidente</p>
            <p><b>Enfants : </b></p>
            <p>Maël CP / Maloé PS</p>
        </div>
        <div class="vicePresident">
            <div class="vicePresident1">
                <img src="assets/front/images/photostephanie.jpg">
            </div>
            <h3>Stéphanie</h3>
            <p>Vice-Présidente</p>
            <p>dévelopeuse web</p>
            <p><b>Enfants : </b></p>
            <p>Mathéo GS</p>
        </div>
        <div class="treasurer">
            <h3>Élise</h3>
            <p>Trésorière</p>
            <p><b>Enfants : </b></p>
            <p>Martin CE1 / Hugo GS</p>
        </div>
        <div class="secretary">
            <h3>Noémie</h3>
            <p>Secrétaire</p>
            <p><b>Enfants : </b></p>
            <p>Maïwenn GS</p>
        </div>
        <div class="assistantSecretary">
            <h3>Bénédicte</h3>
            <p>Secrétaire assistante</p>
            <p><b>Enfants : </b></p>
            <p>Simon CP</p>
        </div>

    </main>